### PR TITLE
add access to check loading status

### PR DESCRIPTION
**Pull request by brightsider**

### CODE REVIEW

**Comment by pronebird** [comment]
Nice! How about renaming `loading` to `animatingInfiniteScroll` ? I know it's pretty long name but it's less generic, less chance of methods clash. I don't use prefixes for methods (because they are ugly).

**Comment by brightsider** [comment]
I'm change property name. Can you make update of Cocoa Pod version with this update?

**Comment by pronebird** [comment]
Thanks @brightsider! In a minute.

**Comment by pronebird** [comment]
@brightsider 0.7.3 includes this patch. :tada:

**Comment by brightsider** [comment]
Thanks @pronebird!

**Pull request merged**
