### PR TITLE
Updated for Swift 2.2, Support for Carthage

### PR DESCRIPTION
**Pull request by maximveksler**

### CODE REVIEW

**Comment by pronebird** [comment]
This PR looks pretty legit to me. I'll test and merge it in the morning. Thanks a lot! :+1:

**Comment by pronebird** [comment]
I think your issue with Carthage was related to the fact that there was no tag that would cover Carthage support that was added with #26. Would you please mind to separate Swift 2.2 changes into different PR? Otherwise I can cherry pick them. Also, I am certainly not able to compile it with Xcode 7.2, therefore I'll probably merge your PR into branch and push it to master when Xcode 7.3 is released.

**Comment by maximveksler** [comment]
Xcode 7.3 has been released with Swift 2.2. 

Can we merge this please?

**Comment by pronebird** [comment]
I apologize for delay. I just installed 7.3 and I cherry-picked Swift 2.2 upgrade. Everything works fine. I don't think we have to share demo app's scheme (at least based on documentation, it's main purpose is continuous integration) – https://developer.apple.com/library/ios/recipes/xcode_help-scheme_editor/Articles/SchemeShare.html

I have to close this PR since it's only partially merged.

**Pull request closed without merging**
