### PR TITLE
Trigger offset added

### PR DESCRIPTION
**Pull request by GorkaMM**
I added a property to set an offset between the real end of the scroll view content and the scroll position, so the handler can be triggered before reaching end. I also updated the example.

### CODE REVIEW

**Comment by GorkaMM** [comment]
If you merge this, please release a new version.

Thank you!

**Comment by pronebird** [comment]
Hi, Thanks for your PR. I am curious, what's the use case for that?

p.s.: a pod spec with link to your fork is a part of PR now :-)

**Comment by GorkaMM** [comment]
Hi,

I added this because I wanted the fetching of more data to happen before the user really reached the end, so it could be there faster for him/her. I don't know if this will affect any other calculations you perform in the Category though.

Thank you!

**Comment by pronebird** [comment]
Alright, I see. 

I need to test it first, because we have couple of edge cases like when there is not much content in scrollview, we add extra bottom inset to position scroll indicator below visible bounds.

Also, maybe it would be good to use relative dimensions instead of points. (e.g. preload when user is half-way through, 0..1)

**Comment by pronebird** [comment]
I've been thinking about that improvement and I suggest that we implement it as a block that receives enough information to calculate custom offset.

For example:

    triggerOffset = triggerOffset( proposedTriggerOffset, contentSize, scrollViewSize );

Custom implementation that preloads more content when we reach 75% of scroll view content would look then as following:

    CGPoint(^customOffset)(CGPoint proposed, CGSize contentSize, CGSize scrollViewSize) {
        return proposed.y - contentSize.height * 0.25;
    };

**Comment by pronebird** [comment]
I addressed this improvement in the following commits:

1. Added custom action offset handler: commit b008db705878adb5728830c91e59efcf2416f0fe
2. Added demo handler: commit 97a50356bae165344e737d8306382e069074843c

Default formula is: 

`content.height or bounds.height (whatever is larger) – bounds.height + originalBottomInset`

Since trigger offset can be customized, I expect scroll view will be spamming infinite scroll handler in case if there is no more content to preload and content area does not grow.

But the good thing, due to our delayed messaging system, it won't be spamming it all the time, but only when scroll view stops.

Not sure if that should be addressed.

I would be grateful if you could take a look at custom-action-offset branch and test it.

**Comment by whitefoxy** [comment]
When this feature will be released?

**Comment by pankkor** [comment]
This is definitely a must have feature for seamless infinite scrolling experience

**Comment by zvonicek** [comment]
This feature is really needed and I'd love to see it merged!

**Comment by maximveksler** [comment]
Sounds like a good idea, who tested the branch and can confirm no issues?

**Comment by pankkor** [comment]
I've merged it into my fork and used it on production. No issues spotted so far

**Comment by zvonicek** [comment]
I'm testing this PR too and it works nicely.

**Comment by mamouneyya** [comment]
@pronebird Honestly, I am against the relative dimension idea, as the 50% would be translated to something like 1000+ points after a large number of scrolls in a very long scroll view implementation (e.g. Infinite news feed). The point-based fixed distance sounds more logical to me.

**Comment by pronebird** [comment]
I had to manually merge a part of it due to lots of changes since the PR. This is now a part of 0.9.1 and available on CocoaPods. Thanks everyone for discussion and testing, @GorkaMM for implementation!

**Pull request closed without merging**
