### PR TITLE
Add startInfiniteScrollHandler method for UIView+InfiniteScroll

### PR DESCRIPTION
**Pull request by edopelawi**

### CODE REVIEW

**Comment by pronebird** [comment]
#12 is relevant to this feature.

**Comment by edopelawi** [comment]
Thanks for reviewing my PR! I'll add the missing points and take a look on #12, then.

**Comment by pronebird** [comment]
Thanks again for your PR.

However, I implemented this in https://github.com/pronebird/UIScrollView-InfiniteScroll/tree/feature/begin-infinite-scroll

Please see #12 for change list. My PR is a little more comprehensive as it covers such issues as initial loading and scroll back to top, issues with self-sizing cells and scroll to bottom. Also, allows scroll to bottom when manually starting infinite scroll in both collection views and table views.

**Comment by edopelawi** [comment]
Hey @pronebird, apologies for the late reply.

Sure thing man, checking out your PR now! Thanks for letting me know :)

**Comment by pronebird** [comment]
Thanks again for your efforts. This feature has been released with 1.0.0.

**Pull request closed without merging**
